### ISSUE TITLE
worker handle with while loop

### ISSUE THREAD

**Issue by churongcon** [simplecto/screenshots#32]
Hello,

I see screenshot_worker.py that you use while loop true for handle

```
 def handle(self, *args, **options):

        while True:
```

when I run manage.py screenshot_worker in terminal, I think it will neverstop. how to run manage.py runserver 0.0.0.0:8000

**Comment by undernewmanagement** [comment]
Yes, this is the purpose. It is a worker and intended to run forever. Please see the Django docs for running the server vs. managed commands.

https://docs.djangoproject.com/en/3.1/howto/custom-management-commands/
